### ISSUE TITLE
Tasks that should have been retried directly fail to finish

### ISSUE THREAD

**Issue by zhanghuidouble** [apache/incubator-dolphinscheduler#869]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

MasterExecThread.runProcess will updateProcessInstanceState after run task ,  the method of   getProcessInstanceState will check if processFailed ，the code is

![image](https://user-images.githubusercontent.com/28583581/65487160-d76c1e00-ded8-11e9-8ed2-dfd33ac3c1e8.png)

but One case is that readyToSubmitTaskList.size !=0 but activeTaskNode.size = 0

the case like this:

1. create a DAG like this 

[{"connects":[],"createTime":1569291957000,"desc":"超时失败告警重试","flag":"YES","id":21,"locations":{"tasks-77628":{"targetarr":"","x":195,"name":"失败重试2次","y":431},"tasks-37810":{"targetarr":"","x":250,"name":"超时失败","y":133},"tasks-54599":{"targetarr":"","x":181,"name":"超时告警","y":289}},"name":"超时失败告警重试","processData":{"globalParams":[],"tasks":[{"depList":[],"dependence":"{}","desc":"","forbidden":false,"id":"tasks-37810","maxRetryTimes":0,"name":"超时失败","params":"{\"resourceList\":[],\"localParams\":[],\"rawScript\":\"sleep 70\"}","preTasks":"[]","retryInterval":1,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":true,"interval":1,"strategy":"FAILED"},"timeout":"{\"strategy\":\"FAILED\",\"interval\":1,\"enable\":true}","type":"SHELL","workerGroupId":"-1"},{"depList":[],"dependence":"{}","desc":"","forbidden":false,"id":"tasks-54599","maxRetryTimes":0,"name":"超时告警","params":"{\"resourceList\":[],\"localParams\":[],\"rawScript\":\"sleep 70\"}","preTasks":"[]","retryInterval":1,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":true,"interval":1,"strategy":"WARN"},"timeout":"{\"strategy\":\"WARN\",\"interval\":1,\"enable\":true}","type":"SHELL","workerGroupId":"-1"},{"depList":[],"dependence":"{}","desc":"","forbidden":false,"id":"tasks-77628","maxRetryTimes":2,"name":"失败重试2次","params":"{\"resourceList\":[],\"localParams\":[],\"rawScript\":\"风风光光哼哼唧唧黑胡椒\"}","preTasks":"[]","retryInterval":1,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":false,"interval":0},"timeout":"{\"strategy\":\"\",\"interval\":null,\"enable\":false}","type":"SHELL","workerGroupId":"-1"}],"timeout":0},"projectId":12,"projectName":"中文qwe123_","receivers":"","receiversCc":"","releaseState":"ONLINE","timeout":0,"updateTime":1569291957000,"userId":"","version":0}]

2.  start

3. the task "失败重试2次"  Expect to retry 2 but only 1 

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
please use English for better global communication!

**Comment by qiaozhanwei** [comment]
please test under dev1.1.0
![3](https://user-images.githubusercontent.com/23756105/65681558-b7c92700-e08b-11e9-90da-d797ba5ffc71.png)

**Comment by zhanghuidouble** [comment]
I tried with the  [OnLineDemo](http://106.75.43.194:8888/#/projects/task-instance) ,it is still  not wright. if just tried the simple task node  retry it is ok

**Comment by lenboo** [comment]
@zhanghuidouble 
this question are already resolved on new version 1.2.0, the online demo also has also been updated synchronously, please check it, and close this issue if it's ok.
In addition, please update the issue title to english.
thank you very much for your contribution!

**Comment by zhanghuidouble** [comment]
Now there is still a problem with the online demo


![image](https://user-images.githubusercontent.com/28583581/70112076-40b59d80-168f-11ea-9baa-73044842988e.png)

**Comment by zhanghuidouble** [comment]
please retry with the DAG

[retry_demo.zip](https://github.com/apache/incubator-dolphinscheduler/files/3919959/retry_demo.zip)

**Comment by zhanghuidouble** [comment]
[retry_demo.zip](https://github.com/apache/incubator-dolphinscheduler/files/3919961/retry_demo.zip)

**Comment by lenboo** [comment]
yes, the retry times would be 1 when you set the max retry to 2. because  retry times contains the first running .

**Comment by zhanghuidouble** [comment]
No, the number of retries should be 2

![image](https://user-images.githubusercontent.com/28583581/70212403-2c969c80-1772-11ea-980c-17d531c61bc1.png)

**Comment by gabrywu** [comment]
> @zhanghuidouble
> this question is already resolved on new version 1.2.0, the online demo also has also been updated synchronously, please check it, and close this issue if it's ok.
> In addition, please update the issue title to english.
> thank you very much for your contribution!

@zhanghuidouble you can try a newer version, or fix it by yourself referring to the 1.2.0
